### ISSUE TITLE
apply different kind of time

### ISSUE THREAD

**Issue by buchslava** [vizabi/vizabi-ddfcsv-reader#12]
regarding this: https://docs.google.com/document/d/1Cd2kEH5w3SRJYaDcu-M4dU5SY8No84T3g-QlNSW6pIE/edit#heading=h.oafc7aswaafy

**Comment by jheeffer** [comment]
This is not an issue anymore, no need for doing this. Current time handling is good : ).

Just to be sure: current time handling is concept_type MUST be time and then year/day/month/quarter/week is inferred from values, right?
