### ISSUE TITLE
Response contains subset of expected response for schema-queries

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi-ddfcsv-reader#53]
**Reader**: 0.13.0
**Dataset**: https://github.com/Gapminder/ddf--pcbs--census/tree/features/flattened
**Query**: 
```
{
   "select":{
      "key":[
         "key",
         "value"
      ],
      "value":[ ]
   },
   "from":"datapoints.schema"
}
```

**Expected**: returns all availability as given in datapackage.json of dataset

**Actual result**: returns subset of availability as given in datapackage.json of dataset

**Tested case**: `population_both_sexes`
In datapackage.json availability for this concept with key `geo,year` and `migrate_to,year` is defined [here](https://github.com/Gapminder/ddf--pcbs--census/blob/features/flattened/datapackage.json#L5237-L5248) and [here](https://github.com/Gapminder/ddf--pcbs--census/blob/features/flattened/datapackage.json#L10720-L10730).
However, DDFcsv reader does not include `geo,year` and `migrato_to,year` availability in its response:
![image](https://user-images.githubusercontent.com/1596071/32606524-e881169e-c555-11e7-8093-b04da89cb50f.png)

**Additional question:** How can this happen? This seems suuuuuper easy logic. Just read datapackage.json and return whatever is in it.

**Comment by buchslava** [comment]
@jheeffer I found. I use `resources` instead `ddfSchema` in this functionality. My bad, sorry /
